version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  sd:
    build:
      context: ./sd
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./sd/app.py:/app/app.py
      - hf_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    # This mounts your local code into the container so you don't have to
    # rebuild the container every time you change a Ruby file!
    volumes:
      - .:/app
    # Tells Docker to pass your .env file into the container
    env_file:
      - .env
    # Override the DB_HOST to point to the Postgres container
    environment:
      - DB_HOST=db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
      - sd

volumes:
  postgres_data:
  hf_cache: